### ISSUE TITLE
connectToHotspot not returning correct status

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/cordova-hotspot-plugin#4]
Please check the method: `cordova.plugins.hotspot.connectToHotspot`

I think it is not working fine

I get "connected" even if it not

**Comment by webmaster-imaginet** [comment]
cordova.plugins.hotspot.connectToHotspot somtimes return "Connection was not successfull" even if the device is successfully connected to the SSID.

**Comment by webmaster-imaginet** [comment]
in version 0.7.2 I'm getting all the time "Connection was not successfull" even when it is connectet.
I checked it with several devices.

![image](https://cloud.githubusercontent.com/assets/4920443/12702801/788e7408-c83b-11e5-98e1-4339b97ef54b.png)

**Comment by hypery2k** [comment]
Fixed in 0.7.3

**Comment by webmaster-imaginet** [comment]
Hi,

Same issue.
2 different devices - android 4.4.4 & 5.1.1, I'm still get "Connection was not successfull" even if the device is successfully connected to the SSID

**Comment by hypery2k** [comment]
fixed in version 0.7.4

**Comment by webmaster-imaginet** [comment]
I'm still having issues.

I build a very small ionic app only to test this method.
You can get it from this dropbox link (apk + zip with full ionic project): https://www.dropbox.com/sh/kuqmj3xdtod3f6u/AACao9zsSdVJJT4mAEnnwuBda?dl=0

Here you can see a screenshot of wrong password that still give me "Connected" result.
![image](https://cloud.githubusercontent.com/assets/4920443/12816587/f65f16b8-cb55-11e5-8718-c399bc9010b6.png)

**Comment by hypery2k** [comment]
the API proposed to use don't deliver this info. I try to add this

**Comment by hypery2k** [comment]
should work with version 0.7.5

**Comment by webmaster-imaginet** [comment]
The problem is that the method return "Connection was successfull" on any other Wi-Fi that the device connected to.
But the method meant to connect to a specific SSID & Password.
If the device has no other Wi-Fi configured on it, then it will work fine.
But when you have some other configured Wi-Fi on the device, the method return a wrong result since "hotspot.isConnectedToAP()" doesn't check the SSID name.

**Comment by webmaster-imaginet** [comment]
**Version 0.7.6 return error call back on any connection result.**

Sometimes the method connect to the correct Wi-Fi & other times it connected to a different configured Wifi on the device - even if you gave it a correct SSID + Password.

I updae the test app apk in the dropbox link: https://www.dropbox.com/sh/kuqmj3xdtod3f6u/AACao9zsSdVJJT4mAEnnwuBda?dl=0

**Comment by hypery2k** [comment]
I don't think I can change this the API I'm using is not providing any deeper result check for this. But I'm try to hack around

**Comment by hypery2k** [comment]
I've verified with plugin 0.7.7 and works for my with Android 5.0.3 in all cases
